server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  transaction:
    rollback-on-commit-failure: true
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 120
      maximumPoolSize: 150
app:
  api:
    factory: monk