server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  transaction:
    rollback-on-commit-failure: true
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 120
      maximumPoolSize: 150
